<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="CIE 9709 Paper 5 Probability and Statistics 1, syllabus 5.3.">

<title>5.3 Probability – CIE Mathematics 9709</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../paper-5/discrete-random-variables.html" rel="next">
<link href="../paper-5/permutations-and-combinations.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a2a938b4dd5711f7a799c87bd16ba44c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../paper-5/representation-of-data.html">Paper 5 · Probability and Statistics 1</a></li><li class="breadcrumb-item"><a href="../paper-5/probability.html">5.3 Probability</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="搜索" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">CIE Mathematics 9709</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="搜索"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">学习首页</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 1 · Pure Mathematics 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/quadratics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.1 Quadratics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.2 Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/coordinate-geometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.3 Coordinate geometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/circular-measure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.4 Circular measure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/trigonometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.5 Trigonometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.6 Series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/differentiation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.7 Differentiation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-1/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.8 Integration</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 2 · Pure Mathematics 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.1 Algebra</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/logarithmic-and-exponential-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.2 Logarithmic and exponential functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/trigonometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.3 Trigonometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/differentiation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.4 Differentiation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.5 Integration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-2/numerical-solution-of-equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.6 Numerical solution of equations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 3 · Pure Mathematics 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/algebra-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Algebra - Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/logarithmic-and-exponential-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Logarithmic and exponential functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/trigonometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Trigonometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/differentiation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Differentiation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Integration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/numerical-solution-of-equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Numerical solution of equations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/differential-equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Differential equations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-3/complex-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Complex numbers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 4 · Mechanics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-4/forces-and-equilibrium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Forces and equilibrium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-4/kinematics-of-motion-in-a-straight-line.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Kinematics of motion in a straight line</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-4/momentum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Momentum</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-4/newtons-laws-of-motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Newton’s laws of motion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-4/energy-work-and-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Energy, work and power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 5 · Probability and Statistics 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-5/representation-of-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.1 Representation of data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-5/permutations-and-combinations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.2 Permutations and combinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-5/probability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">5.3 Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-5/discrete-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.4 Discrete random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-5/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.5 The normal distribution</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper 6 · Probability and Statistics 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-6/poisson-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.1 The Poisson distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-6/linear-combinations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.2 Linear combinations of random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-6/continuous-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.3 Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-6/sampling-and-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.4 Sampling and estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../paper-6/hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.5 Hypothesis tests</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">该页面内容</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#core-knowledge" id="toc-core-knowledge" class="nav-link" data-scroll-target="#core-knowledge">1. Core knowledge</a>
  <ul class="collapse">
  <li><a href="#sample-space-and-elementary-events" id="toc-sample-space-and-elementary-events" class="nav-link" data-scroll-target="#sample-space-and-elementary-events">Sample space and elementary events</a></li>
  <li><a href="#event-notation" id="toc-event-notation" class="nav-link" data-scroll-target="#event-notation">Event notation</a></li>
  <li><a href="#addition-and-multiplication" id="toc-addition-and-multiplication" class="nav-link" data-scroll-target="#addition-and-multiplication">Addition and multiplication</a></li>
  <li><a href="#mutually-exclusive-and-independent" id="toc-mutually-exclusive-and-independent" class="nav-link" data-scroll-target="#mutually-exclusive-and-independent">Mutually exclusive and independent</a></li>
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability">Conditional probability</a></li>
  <li><a href="#tree-diagrams" id="toc-tree-diagrams" class="nav-link" data-scroll-target="#tree-diagrams">Tree diagrams</a></li>
  <li><a href="#venn-diagrams-and-two-way-tables" id="toc-venn-diagrams-and-two-way-tables" class="nav-link" data-scroll-target="#venn-diagrams-and-two-way-tables">Venn diagrams and two-way tables</a></li>
  <li><a href="#常见失分点" id="toc-常见失分点" class="nav-link" data-scroll-target="#常见失分点">常见失分点</a></li>
  </ul></li>
  <li><a href="#note-worked-examples" id="toc-note-worked-examples" class="nav-link" data-scroll-target="#note-worked-examples">2. Note worked examples</a>
  <ul class="collapse">
  <li><a href="#worked-example-1-a-fair-five-sided-spinner" id="toc-worked-example-1-a-fair-five-sided-spinner" class="nav-link" data-scroll-target="#worked-example-1-a-fair-five-sided-spinner">Worked example 1 · A fair five-sided spinner</a></li>
  <li><a href="#worked-example-2-independent-and-mutually-exclusive-events" id="toc-worked-example-2-independent-and-mutually-exclusive-events" class="nav-link" data-scroll-target="#worked-example-2-independent-and-mutually-exclusive-events">Worked example 2 · Independent and mutually exclusive events</a></li>
  <li><a href="#worked-example-3-venn-diagram-and-basic-events" id="toc-worked-example-3-venn-diagram-and-basic-events" class="nav-link" data-scroll-target="#worked-example-3-venn-diagram-and-basic-events">Worked example 3 · Venn diagram and basic events</a></li>
  <li><a href="#worked-example-4-complement-and-intersection" id="toc-worked-example-4-complement-and-intersection" class="nav-link" data-scroll-target="#worked-example-4-complement-and-intersection">Worked example 4 · Complement and intersection</a></li>
  <li><a href="#worked-example-5-conditional-probability" id="toc-worked-example-5-conditional-probability" class="nav-link" data-scroll-target="#worked-example-5-conditional-probability">Worked example 5 · Conditional probability</a></li>
  <li><a href="#worked-example-6-two-way-table" id="toc-worked-example-6-two-way-table" class="nav-link" data-scroll-target="#worked-example-6-two-way-table">Worked example 6 · Two-way table</a></li>
  <li><a href="#worked-example-7-a-multi-stage-tree-diagram" id="toc-worked-example-7-a-multi-stage-tree-diagram" class="nav-link" data-scroll-target="#worked-example-7-a-multi-stage-tree-diagram">Worked example 7 · A multi-stage tree diagram</a></li>
  <li><a href="#worked-example-8-three-event-venn-diagram" id="toc-worked-example-8-three-event-venn-diagram" class="nav-link" data-scroll-target="#worked-example-8-three-event-venn-diagram">Worked example 8 · Three-event Venn diagram</a></li>
  </ul></li>
  <li><a href="#verified-paper-5-questions" id="toc-verified-paper-5-questions" class="nav-link" data-scroll-target="#verified-paper-5-questions">3. Verified Paper 5 questions</a>
  <ul class="collapse">
  <li><a href="#question-1-970951on20-q1ab" id="toc-question-1-970951on20-q1ab" class="nav-link" data-scroll-target="#question-1-970951on20-q1ab">Question 1 · 9709/51/O/N/20 Q1(a–b)</a></li>
  <li><a href="#question-2-970953mj20-q1ab" id="toc-question-2-970953mj20-q1ab" class="nav-link" data-scroll-target="#question-2-970953mj20-q1ab">Question 2 · 9709/53/M/J/20 Q1(a–b)</a></li>
  <li><a href="#question-3-970952on20-q4ad" id="toc-question-3-970952on20-q4ad" class="nav-link" data-scroll-target="#question-3-970952on20-q4ad">Question 3 · 9709/52/O/N/20 Q4(a–d)</a></li>
  <li><a href="#question-4-970952mj20-q2ac" id="toc-question-4-970952mj20-q2ac" class="nav-link" data-scroll-target="#question-4-970952mj20-q2ac">Question 4 · 9709/52/M/J/20 Q2(a–c)</a></li>
  <li><a href="#question-5-970951on21-q3" id="toc-question-5-970951on21-q3" class="nav-link" data-scroll-target="#question-5-970951on21-q3">Question 5 · 9709/51/O/N/21 Q3</a></li>
  <li><a href="#question-6-970953on21-q7ac" id="toc-question-6-970953on21-q7ac" class="nav-link" data-scroll-target="#question-6-970953on21-q7ac">Question 6 · 9709/53/O/N/21 Q7(a–c)</a></li>
  <li><a href="#question-7-970953mj22-q6ac" id="toc-question-7-970953mj22-q6ac" class="nav-link" data-scroll-target="#question-7-970953mj22-q6ac">Question 7 · 9709/53/M/J/22 Q6(a–c)</a></li>
  <li><a href="#question-8-970953on22-q7ac" id="toc-question-8-970953on22-q7ac" class="nav-link" data-scroll-target="#question-8-970953on22-q7ac">Question 8 · 9709/53/O/N/22 Q7(a–c)</a></li>
  <li><a href="#question-9-970952mj24-q2ab" id="toc-question-9-970952mj24-q2ab" class="nav-link" data-scroll-target="#question-9-970952mj24-q2ab">Question 9 · 9709/52/M/J/24 Q2(a–b)</a></li>
  <li><a href="#question-10-970953mj24-q3ab" id="toc-question-10-970953mj24-q3ab" class="nav-link" data-scroll-target="#question-10-970953mj24-q3ab">Question 10 · 9709/53/M/J/24 Q3(a–b)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../paper-5/representation-of-data.html">Paper 5 · Probability and Statistics 1</a></li><li class="breadcrumb-item"><a href="../paper-5/probability.html">5.3 Probability</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">5.3 Probability</h1>
<p class="subtitle lead">Sample spaces · events · independence · conditional probability</p>
</div>

<div>
  <div class="description">
    CIE 9709 Paper 5 Probability and Statistics 1, syllabus 5.3.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>本节考纲要求
</div>
</div>
<div class="callout-body-container callout-body">
<p>本页依据 9709 Mathematics 2026–2027 syllabus 5.3，覆盖：</p>
<ul>
<li>evaluate probabilities in simple cases by enumeration of equiprobable elementary events, or by calculation using permutations or combinations;</li>
<li>use addition and multiplication of probabilities, as appropriate, in simple cases;</li>
<li>understand exclusive and independent events, including deciding whether two events are independent;</li>
<li>calculate and use conditional probabilities in simple cases, including situations represented by a sample space or a tree diagram.</li>
</ul>
<p>真题均来自本地原始 QP，并与对应 mark scheme 核对；题目保持原文，不改写或编造。考纲说明不要求显式使用一般的 <span class="math inline">P(A\cup B)</span> 公式，但理解 union、intersection、complement 和 conditional probability 仍是本节基础。</p>
</div>
</div>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<div class="study-card">
<ul class="task-list">
<li><label><input type="checkbox">从 equiprobable sample space 枚举 favourable outcomes 并计算概率</label></li>
<li><label><input type="checkbox">正确解释 <span class="math inline">A\cap B</span>、<span class="math inline">A\cup B</span>、<span class="math inline">A'</span> 和 “given that”</label></li>
<li><label><input type="checkbox">使用 addition rule、multiplication rule 和 complement</label></li>
<li><label><input type="checkbox">判断 mutually exclusive 与 independent，不把两者混淆</label></li>
<li><label><input type="checkbox">读取和绘制 tree diagrams、Venn diagrams 与 two-way tables</label></li>
<li><label><input type="checkbox">用 <span class="math inline">P(A\mid B)=P(A\cap B)/P(B)</span> 处理简单条件概率</label></li>
</ul>
</div>
</section>
<section id="core-knowledge" class="level2">
<h2 class="anchored" data-anchor-id="core-knowledge">1. Core knowledge</h2>
<section id="sample-space-and-elementary-events" class="level3">
<h3 class="anchored" data-anchor-id="sample-space-and-elementary-events">Sample space and elementary events</h3>
<p>An <strong>experiment</strong> 是一个可观察结果的重复过程；所有可能结果组成 sample space <span class="math inline">S</span>。如果所有 elementary outcomes equiprobable，则</p>
<p><span class="math display">
P(A)=\frac{\text{number of outcomes in }A}{\text{number of outcomes in }S}.
</span></p>
<p>例如两个公平六面骰子有 <span class="math inline">6\times6=36</span> 个有序结果。即使总分相同，<span class="math inline">(2,3)</span> 和 <span class="math inline">(3,2)</span> 仍是两个不同的 elementary outcomes。</p>
</section>
<section id="event-notation" class="level3">
<h3 class="anchored" data-anchor-id="event-notation">Event notation</h3>
<p>若 <span class="math inline">A</span>、<span class="math inline">B</span> 是 events：</p>
<p><span class="math display">
A\cap B \quad\text{表示 A and B},
</span></p>
<p><span class="math display">
A\cup B \quad\text{表示 A or B or both},
</span></p>
<p><span class="math display">
A' \quad\text{表示 not A},
\qquad
P(A')=1-P(A).
</span></p>
<p>如果 <span class="math inline">A</span> 与 <span class="math inline">B</span> 互斥，则不能同时发生，<span class="math inline">A\cap B=\varnothing</span>，因此</p>
<p><span class="math display">
P(A\cup B)=P(A)+P(B).
</span></p>
<p>对于不一定互斥的两个事件，重叠部分不能重复计算：</p>
<p><span class="math display">
P(A\cup B)=P(A)+P(B)-P(A\cap B).
</span></p>
</section>
<section id="addition-and-multiplication" class="level3">
<h3 class="anchored" data-anchor-id="addition-and-multiplication">Addition and multiplication</h3>
<p>“OR” 通常对应相加，特别是当列出的 cases 互斥时；“AND” 通常对应相乘。沿 tree diagram 的一条完整路径相乘，不同的完整路径再相加：</p>
<p><span class="math display">
P(A\cap B)=P(A)P(B\mid A).
</span></p>
<p>若两个事件独立，则 <span class="math inline">P(B\mid A)=P(B)</span>，所以</p>
<p><span class="math display">
P(A\cap B)=P(A)P(B).
</span></p>
</section>
<section id="mutually-exclusive-and-independent" class="level3">
<h3 class="anchored" data-anchor-id="mutually-exclusive-and-independent">Mutually exclusive and independent</h3>
<p><strong>Mutually exclusive</strong>：两个事件不能同时发生，故 <span class="math inline">P(A\cap B)=0</span>。如果两者概率都为正，它们不可能 independent。</p>
<p><strong>Independent</strong>：一个事件是否发生不改变另一个事件的概率。可以比较</p>
<p><span class="math display">
P(A\cap B)\quad\text{和}\quad P(A)P(B).
</span></p>
<p>相等才是 independent；不相等则不是。</p>
<p>不要把 “mutually exclusive” 和 “independent” 当作同义词：互斥强调不能同时发生，独立强调一个事件不影响另一个事件。</p>
</section>
<section id="conditional-probability" class="level3">
<h3 class="anchored" data-anchor-id="conditional-probability">Conditional probability</h3>
<p>“Given that <span class="math inline">B</span>” 表示 sample space 已经缩小到 <span class="math inline">B</span>。因此</p>
<p><span class="math display">
P(A\mid B)=\frac{P(A\cap B)}{P(B)},
\qquad P(B)&gt;0.
</span></p>
<p>计算时先找 numerator “both <span class="math inline">A</span> and <span class="math inline">B</span>”，再用 given event <span class="math inline">B</span> 作 denominator。条件概率也可以通过 tree diagram 的后续 branch 读取。</p>
</section>
<section id="tree-diagrams" class="level3">
<h3 class="anchored" data-anchor-id="tree-diagrams">Tree diagrams</h3>
<p>Tree diagram 中每条 branch 的概率必须与同一节点发出的其他 branch 概率加起来为 <span class="math inline">1</span>。一条完整路径的概率是 branch probabilities 的乘积；如果题目事件包含多条路径，把这些路径的概率相加。</p>
<p>有 replacement 时，后续 branch probability 通常不变；without replacement 时，分母和分子会随前一结果改变。</p>
</section>
<section id="venn-diagrams-and-two-way-tables" class="level3">
<h3 class="anchored" data-anchor-id="venn-diagrams-and-two-way-tables">Venn diagrams and two-way tables</h3>
<p>Venn diagram 中：</p>
<ul>
<li>overlap 是 <span class="math inline">A\cap B</span>；</li>
<li>两个 bubbles 覆盖的区域是 <span class="math inline">A\cup B</span>；</li>
<li>circle 外部是 complement。</li>
</ul>
<p>Two-way table 的 row total、column total 和 grand total 可以直接给出 marginal probabilities。若给定一行或一列，条件概率的 denominator 应使用对应的 row/column total，而不是 grand total。</p>
</section>
<section id="常见失分点" class="level3">
<h3 class="anchored" data-anchor-id="常见失分点">常见失分点</h3>
<ol type="1">
<li>两个骰子的结果按有序 pair 计数，不要只列不同的总分。</li>
<li>“at least one” 通常用 <span class="math inline">1-P(\text{none})</span> 更快。</li>
<li>“given that” 改变 denominator；不要仍然使用整个 sample space。</li>
<li>路径相乘、路径相加的顺序不能混淆。</li>
<li>判断 independent 要比较两个数，不是因为两个事件“看起来没有关系”就直接下结论。</li>
</ol>
</section>
</section>
<section id="note-worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="note-worked-examples">2. Note worked examples</h2>
<p>每个 worked example 单独成卡片；图片均来自原始 <code>2. Probability.pdf</code> 的内嵌资源独立提取，不使用页面截图。</p>
<section id="worked-example-1-a-fair-five-sided-spinner" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-1-a-fair-five-sided-spinner">Worked example 1 · A fair five-sided spinner</h3>
<p>A fair, five-sided spinner has its sides labelled <span class="math inline">2,5,8,10</span> and <span class="math inline">11</span>. Find, from one spin, the probability that the spinner shows:</p>
<ol type="i">
<li><p><span class="math inline">8</span>;</p></li>
<li><p>a prime number;</p></li>
<li><p>an odd prime number;</p></li>
<li><p>a number other than <span class="math inline">5</span>.</p></li>
</ol>
<p>All five outcomes are equally likely. Hence</p>
<p><span class="math display">
P(8)=\frac15,
\qquad
P(\text{prime})=P(2\text{ or }5\text{ or }11)=\frac35,
</span></p>
<p><span class="math display">
P(\text{odd prime})=P(5\text{ or }11)=\frac25,
\qquad
P(\text{not }5)=\frac45.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-01.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note spinner worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-2-independent-and-mutually-exclusive-events" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-2-independent-and-mutually-exclusive-events">Worked example 2 · Independent and mutually exclusive events</h3>
<ol type="a">
<li><p>Two events <span class="math inline">Q</span> and <span class="math inline">R</span> are such that <span class="math inline">P(Q)=0.8</span> and <span class="math inline">P(Q\cap R)=0.1</span>. Given that <span class="math inline">Q</span> and <span class="math inline">R</span> are independent, find <span class="math inline">P(R)</span>.</p></li>
<li><p>Two events <span class="math inline">S</span> and <span class="math inline">T</span> are such that <span class="math inline">P(S)=2P(T)</span>. Given that <span class="math inline">S</span> and <span class="math inline">T</span> are mutually exclusive and that <span class="math inline">P(S\cup T)=0.6</span>, find <span class="math inline">P(S)</span> and <span class="math inline">P(T)</span>.</p></li>
<li><p>A fair five-sided spinner has sides labelled <span class="math inline">2,3,5,7,11</span>. Find the probability that it lands on a number greater than <span class="math inline">5</span>.</p></li>
</ol>
<p>For (a), independence gives</p>
<p><span class="math display">
0.1=P(Q)P(R)=0.8P(R),
\qquad
\boxed{P(R)=0.125}.
</span></p>
<p>For (b), mutual exclusivity gives <span class="math inline">P(S\cup T)=P(S)+P(T)</span>. Let <span class="math inline">P(T)=t</span>, so <span class="math inline">P(S)=2t</span>:</p>
<p><span class="math display">
2t+t=0.6,
\qquad
\boxed{P(S)=0.4,\;P(T)=0.2}.
</span></p>
<p>For (c), the outcomes greater than <span class="math inline">5</span> are <span class="math inline">7</span> and <span class="math inline">11</span>, so the probability is <span class="math inline">2/5</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-02.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note independent-events worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-3-venn-diagram-and-basic-events" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-3-venn-diagram-and-basic-events">Worked example 3 · Venn diagram and basic events</h3>
<p>40 people were surveyed about which games consoles they owned. 8 owned a PlayStation 5 (<span class="math inline">P</span>) and an Xbox Series X (<span class="math inline">X</span>). 5 owned neither console. Of those people who owned either console, twice as many owned an Xbox Series X only than a PlayStation 5 only. Find the probability that a randomly chosen person:</p>
<ol type="i">
<li><p>owns both consoles;</p></li>
<li><p>owns exactly one console;</p></li>
<li><p>does not own a PlayStation 5.</p></li>
</ol>
<p>Let the number owning only <span class="math inline">P</span> be <span class="math inline">x</span>; only <span class="math inline">X</span> is <span class="math inline">2x</span>. Then</p>
<p><span class="math display">
x+8+2x+5=40 \implies x=9.
</span></p>
<p>Therefore</p>
<p><span class="math display">
P(\text{both})=\frac8{40},
</span></p>
<p><span class="math display">
P(\text{exactly one})=\frac{9+18}{40}=\frac{27}{40},
</span></p>
<p><span class="math display">
P(P')=\frac{5+18}{40}=\frac{23}{40}.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-03.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note Venn-diagram worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-4-complement-and-intersection" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-4-complement-and-intersection">Worked example 4 · Complement and intersection</h3>
<p>The members of a local tennis club decide whether to play in a singles competition (<span class="math inline">S</span>) or a doubles competition (<span class="math inline">D</span>). Given</p>
<p><span class="math display">
P(S)=2P(D),\qquad P(S\cup D)=0.9,\qquad P(S\cap D)=0.3,
</span></p>
<p>find <span class="math inline">P(S')</span>, <span class="math inline">P(S'\cap D)</span>, <span class="math inline">P(S\cup D')</span> and <span class="math inline">P((S\cup D)')</span>.</p>
<p>From <span class="math inline">P(S)=2P(D)</span> and</p>
<p><span class="math display">
P(S\cup D)=P(S)+P(D)-P(S\cap D),
</span></p>
<p>we get <span class="math inline">2d+d-0.3=0.9</span>, so <span class="math inline">P(D)=0.4</span> and <span class="math inline">P(S)=0.8</span>. Hence</p>
<p><span class="math display">
P(S')=1-0.8=0.2,
</span></p>
<p><span class="math display">
P(S'\cap D)=P(D)-P(S\cap D)=0.4-0.3=0.1,
</span></p>
<p><span class="math display">
P(S\cup D')=1-P(S'\cap D)=0.9,
</span></p>
<p><span class="math display">
P((S\cup D)')=1-P(S\cup D)=0.1.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-04.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note complement/intersection worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-5-conditional-probability" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-5-conditional-probability">Worked example 5 · Conditional probability</h3>
<p>The probabilities of two events, <span class="math inline">A</span> and <span class="math inline">B</span>, are <span class="math inline">P(A)=0.4</span> and <span class="math inline">P(B)=0.5</span>. It is also known that <span class="math inline">P(A\cap B)=0.2</span>. Find</p>
<ol type="a">
<li><p><span class="math inline">P(A\mid B)</span>;</p></li>
<li><p><span class="math inline">P(B\mid A')</span>;</p></li>
<li><p><span class="math inline">P((A\cap B)\mid(A\cup B))</span>.</p></li>
</ol>
<p>Using <span class="math inline">P(A\mid B)=P(A\cap B)/P(B)</span>:</p>
<p><span class="math display">
P(A\mid B)=\frac{0.2}{0.5}=\boxed{0.4}.
</span></p>
<p>Since <span class="math inline">P(A')=0.6</span> and <span class="math inline">P(B\cap A')=P(B)-P(A\cap B)=0.3</span>,</p>
<p><span class="math display">
P(B\mid A')=\frac{0.3}{0.6}=\boxed{0.5}.
</span></p>
<p>Also <span class="math inline">P(A\cup B)=0.4+0.5-0.2=0.7</span>, so</p>
<p><span class="math display">
P((A\cap B)\mid(A\cup B))=\frac{0.2}{0.7}=\boxed{\frac27}.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-05.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note conditional-probability worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-6-two-way-table" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-6-two-way-table">Worked example 6 · Two-way table</h3>
<p>The incomplete two-way table below shows the type of main meal provided by 80 owners to their cats or dogs.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Dry food</th>
<th style="text-align: right;">Wet food</th>
<th style="text-align: right;">Raw food</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dog</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="even">
<td>Cat</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">80</td>
</tr>
</tbody>
</table>
<p>For example,</p>
<p><span class="math display">
P(\text{cat and raw})=\frac4{80},
</span></p>
<p><span class="math display">
P(\text{dog or wet})=\frac{47}{80}+\frac{47}{80}-\frac{28}{80}=\frac{33}{40},
</span></p>
<p><span class="math display">
P(\text{raw}\mid\text{dog})=\frac8{47},
\qquad
P(\text{cat}\mid\text{dry})=\frac{10}{21}.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-06.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note two-way-table worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-7-a-multi-stage-tree-diagram" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-7-a-multi-stage-tree-diagram">Worked example 7 · A multi-stage tree diagram</h3>
<p>The event <span class="math inline">F</span> has a 75% probability of occurring. The event <span class="math inline">W</span> follows event <span class="math inline">F</span>, and if <span class="math inline">F</span> has occurred, event <span class="math inline">W</span> has an 80% chance of occurring. It is also known that <span class="math inline">P(F'\cap W)=0.15</span>. Find the relevant joint probabilities.</p>
<p>The branch probabilities are</p>
<p><span class="math display">
P(F)=0.75,quad P(F')=0.25,quad P(W\mid F)=0.8,quad P(W'\mid F)=0.2.
</span></p>
<p>Thus</p>
<p><span class="math display">
P(F\cap W)=0.75\times0.8=0.6,
</span></p>
<p><span class="math display">
P(F\cap W')=0.75\times0.2=0.15,
</span></p>
<p>and, because <span class="math inline">P(F'\cap W)=0.15</span>, the final branch probability is</p>
<p><span class="math display">
P(F'\cap W')=1-(0.6+0.15+0.15)=0.1.
</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-07.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note multi-stage tree worked solution.</figcaption>
</figure>
</div>
</section>
<section id="worked-example-8-three-event-venn-diagram" class="level3 worked-example">
<h3 class="anchored" data-anchor-id="worked-example-8-three-event-venn-diagram">Worked example 8 · Three-event Venn diagram</h3>
<p>Three events <span class="math inline">A</span>, <span class="math inline">B</span> and <span class="math inline">C</span> are such that <span class="math inline">A</span> and <span class="math inline">C</span> are mutually exclusive,</p>
<p><span class="math display">
P(A\cap B)=0.2,\quad P(B\cap C)=0.3,\quad P((A\cup B\cup C)')=0.1,
</span></p>
<p><span class="math display">
P(B)=0.7,\qquad P(A')=0.75.
</span></p>
<p>Since <span class="math inline">A</span> and <span class="math inline">C</span> are mutually exclusive, the regions are</p>
<p><span class="math display">
P(A\text{ only})=0.75-0.7=0.05,
</span></p>
<p><span class="math display">
P(C\text{ only})=1-(0.05+0.2+0.3+0.2+0.1)=0.15.
</span></p>
<p>For example,</p>
<p><span class="math display">
P(A\mid B)=\frac{P(A\cap B)}{P(B)}=\frac{0.2}{0.7}=\boxed{\frac27},
</span></p>
<p>and</p>
<p><span class="math display">
P(A'\mid C)=\frac{P(A'\cap C)}{P(C)}=1,
</span></p>
<p>because <span class="math inline">A</span> and <span class="math inline">C</span> are mutually exclusive.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/probability/worked-example-08.webp" class="note-figure img-fluid figure-img"></p>
<figcaption>Original Note three-event Venn worked solution.</figcaption>
</figure>
</div>
</section>
</section>
<section id="verified-paper-5-questions" class="level2">
<h2 class="anchored" data-anchor-id="verified-paper-5-questions">3. Verified Paper 5 questions</h2>
<p>以下题组保持原始题干、全部小问和原始分值；答案按对应 mark scheme 的得分路径展开。真题中的 tree diagram 只保留必要图形，图片来自原始 QP 的矢量内容，不使用截图。</p>
<div id="p5-prob-q01" class="question-card">
<section id="question-1-970951on20-q1ab" class="level3">
<h3 class="anchored" data-anchor-id="question-1-970951on20-q1ab">Question 1 · 9709/51/O/N/20 Q1(a–b)</h3>
<p>Two ordinary fair dice, one red and the other blue, are thrown.</p>
<p>Event A is ‘the score on the red die is divisible by 3’.</p>
<p>Event B is ‘the sum of the two scores is at least 9’.</p>
<ol type="a">
<li><p>Find <span class="math inline">P(A\cap B)</span>. <strong>[2]</strong></p></li>
<li><p>Hence determine whether or not the events A and B are independent. <strong>[2]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>There are <span class="math inline">36</span> ordered outcomes. For the red die to be divisible by <span class="math inline">3</span>, its score is <span class="math inline">3</span> or <span class="math inline">6</span>. The favourable outcomes for <span class="math inline">A\cap B</span> are:</li>
</ol>
<ul>
<li>red <span class="math inline">3</span>, blue <span class="math inline">6</span>;</li>
<li>red <span class="math inline">6</span>, blue <span class="math inline">3,4,5,6</span>.</li>
</ul>
<p>Thus there are five favourable outcomes:</p>
<p><span class="math display">
\boxed{P(A\cap B)=\frac5{36}}.
</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">
P(A)=\frac26=\frac13,
\qquad
P(B)=\frac{10}{36}=\frac5{18}.
</span></p>
<p>If independent, <span class="math inline">P(A\cap B)=P(A)P(B)</span>. But</p>
<p><span class="math display">
P(A)P(B)=\frac13\times\frac5{18}=\frac5{54}\ne\frac5{36}.
</span></p>
Therefore <span class="math inline">\boxed{A\text{ and }B\text{ are not independent}}</span>.
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2020/2020/9709_w20_qp_51.pdf, Q1(a–b), with the corresponding 9709/51/O/N/20 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q02" class="question-card">
<section id="question-2-970953mj20-q1ab" class="level3">
<h3 class="anchored" data-anchor-id="question-2-970953mj20-q1ab">Question 2 · 9709/53/M/J/20 Q1(a–b)</h3>
<p>Juan goes to college each day by any one of car or bus or walking. The probability that he goes by car is 0.2, the probability that he goes by bus is 0.45 and the probability that he walks is 0.35. When Juan goes by car, the probability that he arrives early is 0.6. When he goes by bus, the probability that he arrives early is 0.1. When he walks he always arrives early.</p>
<ol type="a">
<li><p>Draw a fully labelled tree diagram to represent this information. <strong>[2]</strong></p></li>
<li><p>Find the probability that Juan goes to college by car given that he arrives early. <strong>[4]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>The first branches are car <span class="math inline">0.2</span>, bus <span class="math inline">0.45</span>, walking <span class="math inline">0.35</span>. The corresponding early/late branches are:</li>
</ol>
<p><span class="math display">
\begin{array}{c|cc}
&amp;\text{early}&amp;\text{not early}\\ \hline
\text{car}&amp;0.6&amp;0.4\\
\text{bus}&amp;0.1&amp;0.9\\
\text{walking}&amp;1&amp;0
\end{array}
</span></p>
<ol start="2" type="a">
<li>The probability of arriving early is</li>
</ol>
<p><span class="math display">
P(E)=0.2(0.6)+0.45(0.1)+0.35(1)=0.515.
</span></p>
<p>The probability of car and early is <span class="math inline">0.2(0.6)=0.12</span>. Therefore</p>
<span class="math display">
P(\text{car}\mid E)=\frac{0.12}{0.515}
=\boxed{\frac{24}{103}\approx0.233}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2020/2020/9709-s20-qp-53.pdf, Q1(a–b), with the corresponding 9709/53/M/J/20 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q03" class="question-card">
<section id="question-3-970952on20-q4ad" class="level3">
<h3 class="anchored" data-anchor-id="question-3-970952on20-q4ad">Question 3 · 9709/52/O/N/20 Q4(a–d)</h3>
<p>In a certain country, the weather each day is classified as fine or rainy. The probability that a fine day is followed by a fine day is 0.75 and the probability that a rainy day is followed by a fine day is 0.4. The probability that it is fine on 1 April is 0.8. The tree diagram below shows the possibilities for the weather on 1 April and 2 April.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/questions/extracted/paper5-probability/2020-on52-q4-tree.svg" class="question-figure img-fluid figure-img"></p>
<figcaption>Original QP tree diagram for 9709/52/O/N/20 Q4(a).</figcaption>
</figure>
</div>
<ol type="a">
<li><p>Complete the tree diagram to show the probabilities. <strong>[1]</strong></p></li>
<li><p>Find the probability that 2 April is fine. <strong>[2]</strong></p></li>
</ol>
<p>Let <span class="math inline">X</span> be the event that 1 April is fine and <span class="math inline">Y</span> be the event that 3 April is rainy.</p>
<ol start="3" type="a">
<li><p>Find the value of <span class="math inline">P(X\cap Y)</span>. <strong>[3]</strong></p></li>
<li><p>Find the probability that 1 April is fine given that 3 April is rainy. <strong>[3]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li><p>Complete branches: after fine, fine <span class="math inline">0.75</span> and rainy <span class="math inline">0.25</span>; after rainy, fine <span class="math inline">0.4</span> and rainy <span class="math inline">0.6</span>.</p></li>
<li></li>
</ol>
<p><span class="math display">
P(\text{fine on 2 April})=0.8(0.75)+0.2(0.4)
=\boxed{0.68}.
</span></p>
<ol start="3" type="a">
<li>Starting with fine on 1 April, 3 April is rainy through two paths:</li>
</ol>
<p><span class="math display">
P(X\cap Y)=0.8(0.75)(0.25)+0.8(0.25)(0.6)
=\boxed{0.27}.
</span></p>
<ol start="4" type="a">
<li>The probability that 3 April is rainy is</li>
</ol>
<p><span class="math display">
P(Y)=0.27+0.2(0.4)(0.25)+0.2(0.6)(0.6)
=0.362.
</span></p>
<p>Therefore</p>
<span class="math display">
P(X\mid Y)=\frac{P(X\cap Y)}{P(Y)}
=\frac{0.27}{0.362}
=\boxed{0.746\text{ (3 s.f.)}}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2020/2020/9709_w20_qp_52.pdf, Q4(a–d), with the corresponding 9709/52/O/N/20 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q04" class="question-card">
<section id="question-4-970952mj20-q2ac" class="level3">
<h3 class="anchored" data-anchor-id="question-4-970952mj20-q2ac">Question 4 · 9709/52/M/J/20 Q2(a–c)</h3>
<p>A total of 500 students were asked which one of four colleges they attended and whether they preferred soccer or hockey. The numbers of students in each category are shown in the following table.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Soccer</th>
<th style="text-align: right;">Hockey</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Amos</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">86</td>
</tr>
<tr class="even">
<td>Benn</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">156</td>
</tr>
<tr class="odd">
<td>Canton</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td>Devar</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">180</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">500</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Find the probability that a randomly chosen student is at Canton college and prefers hockey. <strong>[1]</strong></p></li>
<li><p>Find the probability that a randomly chosen student is at Devar college given that he prefers soccer. <strong>[2]</strong></p></li>
<li><p>One of the students is chosen at random. Determine whether the events ‘the student prefers hockey’ and ‘the student is at Amos college or Benn college’ are independent, justifying your answer. <strong>[2]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li></li>
</ol>
<p><span class="math display">
\boxed{P(\text{Canton and hockey})=\frac{56}{500}=\frac{14}{125}}.
</span></p>
<ol start="2" type="a">
<li>Given soccer, use the soccer column total <span class="math inline">280</span>:</li>
</ol>
<p><span class="math display">
\boxed{P(\text{Devar}\mid\text{soccer})=\frac{120}{280}=\frac37}.
</span></p>
<ol start="3" type="a">
<li>Let <span class="math inline">H</span> be hockey and <span class="math inline">C</span> be Amos or Benn. Then</li>
</ol>
<p><span class="math display">
P(H\cap C)=\frac{32+72}{500}=\frac{104}{500}=0.208,
</span></p>
<p>whereas</p>
<p><span class="math display">
P(H)P(C)=\frac{220}{500}\times\frac{86+156}{500}
=0.44\times0.484=0.21296.
</span></p>
<p>The values are not equal, so</p>
<span class="math display">
\boxed{H\text{ and }C\text{ are not independent}}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2020/2020/9709-s20-qp-52.pdf, Q2(a–c), with the corresponding 9709/52/M/J/20 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q05" class="question-card">
<section id="question-5-970951on21-q3" class="level3">
<h3 class="anchored" data-anchor-id="question-5-970951on21-q3">Question 5 · 9709/51/O/N/21 Q3</h3>
<p>For her bedtime drink, Suki has either chocolate, tea or milk with probabilities 0.45, 0.35 and 0.2 respectively. When she has chocolate, the probability that she has a biscuit is 0.3. When she has tea, the probability that she has a biscuit is 0.6. When she has milk, she never has a biscuit.</p>
<p>Find the probability that Suki has tea given that she does not have a biscuit. <strong>[5]</strong></p>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<p>Let <span class="math inline">N</span> denote no biscuit. The required numerator is</p>
<p><span class="math display">
P(\text{tea}\cap N)=0.35(1-0.6)=0.14.
</span></p>
<p>The probability of no biscuit is</p>
<p><span class="math display">
P(N)=0.45(1-0.3)+0.35(1-0.6)+0.2(1)
=0.315+0.14+0.2=0.655.
</span></p>
<p>Therefore</p>
<span class="math display">
P(\text{tea}\mid N)=\frac{0.14}{0.655}
=\boxed{\frac{28}{131}\approx0.214}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2021/2021/9709_w21_qp_51.pdf, Q3, with the corresponding 9709/51/O/N/21 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q06" class="question-card">
<section id="question-6-970953on21-q7ac" class="level3">
<h3 class="anchored" data-anchor-id="question-6-970953on21-q7ac">Question 6 · 9709/53/O/N/21 Q7(a–c)</h3>
<p>Box A contains 6 red balls and 4 blue balls. Box B contains <span class="math inline">x</span> red balls and 9 blue balls. A ball is chosen at random from box A and placed in box B. A ball is then chosen at random from box B.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/questions/extracted/paper5-probability/2021-on53-q7-tree.svg" class="question-figure img-fluid figure-img"></p>
<figcaption>Original QP tree diagram for 9709/53/O/N/21 Q7(a).</figcaption>
</figure>
</div>
<ol type="a">
<li><p>Complete the tree diagram below, giving the remaining four probabilities in terms of <span class="math inline">x</span>. <strong>[3]</strong></p></li>
<li><p>Show that the probability that both balls chosen are blue is <span class="math inline">\dfrac{4}{x+10}</span>. <strong>[2]</strong></p></li>
</ol>
<p>It is given that the probability that both balls chosen are blue is <span class="math inline">\dfrac16</span>.</p>
<ol start="3" type="a">
<li>Find the probability, correct to 3 significant figures, that the ball chosen from box A is red given that the ball chosen from box B is red. <strong>[5]</strong></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>If a red ball is transferred, box B has <span class="math inline">x+1</span> red and <span class="math inline">9</span> blue balls. If a blue ball is transferred, box B has <span class="math inline">x</span> red and <span class="math inline">10</span> blue balls. Thus the missing branch probabilities are</li>
</ol>
<p><span class="math display">
\frac{x+1}{x+10},\quad\frac9{x+10},\quad
\frac{x}{x+10},\quad\frac{10}{x+10}.
</span></p>
<ol start="2" type="a">
<li>Both selected balls are blue only when the first selection from A is blue:</li>
</ol>
<p><span class="math display">
P(\text{both blue})=\frac4{10}\times\frac{10}{x+10}
=\boxed{\frac4{x+10}}.
</span></p>
<ol start="3" type="a">
<li>From <span class="math inline">4/(x+10)=1/6</span>,</li>
</ol>
<p><span class="math display">
6\times4=x+10\implies x=14.
</span></p>
<p>Now</p>
<p><span class="math display">
P(A_R\cap B_R)=\frac6{10}\times\frac{15}{24}=\frac38,
</span></p>
<p>and</p>
<p><span class="math display">
P(B_R)=\frac6{10}\times\frac{15}{24}
+\frac4{10}\times\frac{14}{24}
=\frac{73}{120}.
</span></p>
<p>Therefore</p>
<span class="math display">
P(A_R\mid B_R)=\frac{3/8}{73/120}
=\frac{45}{73}
=\boxed{0.616\text{ (3 s.f.)}}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2021/2021/9709_w21_qp_53.pdf, Q7(a–c), with the corresponding 9709/53/O/N/21 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q07" class="question-card">
<section id="question-7-970953mj22-q6ac" class="level3">
<h3 class="anchored" data-anchor-id="question-7-970953mj22-q6ac">Question 7 · 9709/53/M/J/22 Q6(a–c)</h3>
<p>Sajid is practising for a long jump competition. He counts any jump that is longer than 6 m as a success. On any day, the probability that he has a success with his first jump is 0.2. For any subsequent jump, the probability of a success is 0.3 if the previous jump was a success and 0.1 otherwise. Sajid makes three jumps.</p>
<ol type="a">
<li><p>Draw a tree diagram to illustrate this information, showing all the probabilities. <strong>[2]</strong></p></li>
<li><p>Find the probability that Sajid has exactly one success given that he has at least one success. <strong>[5]</strong></p></li>
</ol>
<p>On another day, Sajid makes six jumps.</p>
<ol start="3" type="a">
<li>Find the probability that only his first three jumps are successes or only his last three jumps are successes. <strong>[3]</strong></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li><p>First jump: success <span class="math inline">0.2</span>, failure <span class="math inline">0.8</span>. After a success: success <span class="math inline">0.3</span>, failure <span class="math inline">0.7</span>. After a failure: success <span class="math inline">0.1</span>, failure <span class="math inline">0.9</span>.</p></li>
<li><p>The exactly-one-success paths are SFF, FSF and FFS:</p></li>
</ol>
<p><span class="math display">
P(\text{exactly one})
=0.2(0.7)(0.9)+0.8(0.1)(0.7)+0.8(0.9)(0.1)
=0.254.
</span></p>
<p>The probability of at least one success is</p>
<p><span class="math display">
P(\text{at least one})=1-P(FFF)=1-0.8(0.9)(0.9)=0.352.
</span></p>
<p>Hence</p>
<p><span class="math display">
\boxed{P(\text{exactly one}\mid\text{at least one})
=\frac{0.254}{0.352}=\frac{127}{176}\approx0.722}.
</span></p>
<ol start="3" type="a">
<li>The two required paths are SSSFFF and FFFSSS:</li>
</ol>
<p><span class="math display">
P(SSSFFF)=0.2(0.3)(0.3)(0.7)(0.9)(0.9)=0.010206,
</span></p>
<p><span class="math display">
P(FFFSSS)=0.8(0.9)(0.9)(0.1)(0.3)(0.3)=0.005832.
</span></p>
<p>They are mutually exclusive, so</p>
<span class="math display">
\boxed{P=0.010206+0.005832=0.016038}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2022/2022/9709_s22_qp_53.pdf, Q6(a–c), with the corresponding 9709/53/M/J/22 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q08" class="question-card">
<section id="question-8-970953on22-q7ac" class="level3">
<h3 class="anchored" data-anchor-id="question-8-970953on22-q7ac">Question 8 · 9709/53/O/N/22 Q7(a–c)</h3>
<p>Sam and Tom are playing a game which involves a bag containing 5 white discs and 3 red discs. They take turns to remove one disc from the bag at random. Discs that are removed are not replaced into the bag. The game ends as soon as one player has removed two red discs from the bag. That player wins the game. Sam removes the first disc.</p>
<ol type="a">
<li><p>Find the probability that Tom removes a red disc on his first turn. <strong>[2]</strong></p></li>
<li><p>Find the probability that Tom wins the game on his second turn. <strong>[4]</strong></p></li>
<li><p>Find the probability that Sam removes a red disc on his first turn given that Tom wins the game on his second turn. <strong>[2]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>Tom’s first turn is the second draw:</li>
</ol>
<p><span class="math display">
P(T\text{ red})=\frac58\frac37+\frac38\frac27
=\boxed{\frac38}.
</span></p>
<ol start="2" type="a">
<li>For Tom to win on his second turn, the second and fourth draws must both be red. Since there are only three red discs, Sam cannot already have two red discs before the fourth draw in this event:</li>
</ol>
<p><span class="math display">
P(T_1R\text{ and }T_2R)=\frac38\times\frac27
=\boxed{\frac3{28}}.
</span></p>
<ol start="3" type="a">
<li>The numerator for “Sam’s first disc is red and Tom wins on his second turn” is the path R, R, W, R:</li>
</ol>
<p><span class="math display">
P(S_1R\cap T\text{ wins on second})
=\frac38\times\frac27\times\frac56\times\frac15
=\frac1{56}.
</span></p>
<p>Therefore</p>
<span class="math display">
P(S_1R\mid T\text{ wins on second})
=\frac{1/56}{3/28}
=\boxed{\frac16}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2022/2022/9709_w22_qp_53.pdf, Q7(a–c), with the corresponding 9709/53/O/N/22 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q09" class="question-card">
<section id="question-9-970952mj24-q2ab" class="level3">
<h3 class="anchored" data-anchor-id="question-9-970952mj24-q2ab">Question 9 · 9709/52/M/J/24 Q2(a–b)</h3>
<p>Seva has a coin which is biased so that when it is thrown the probability of obtaining a head is <span class="math inline">\frac13</span>. He also has a bag containing 4 red marbles and 5 blue marbles.</p>
<p>Seva throws the coin. If he obtains a head, he selects one marble from the bag at random. If he obtains a tail, he selects two marbles from the bag at random and without replacement.</p>
<ol type="a">
<li><p>Find the probability that Seva selects at least one red marble. <strong>[3]</strong></p></li>
<li><p>Find the probability that Seva obtains a head given that he selects no red marbles. <strong>[2]</strong></p></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>If the coin is a head, the probability of at least one red is <span class="math inline">4/9</span>. If it is a tail, the probability is</li>
</ol>
<p><span class="math display">
1-\frac{\binom52}{\binom92}=1-\frac5{18}=\frac{13}{18}.
</span></p>
<p>Hence</p>
<p><span class="math display">
P(\text{at least one red})
=\frac13\frac49+\frac23\frac{13}{18}
=\boxed{\frac{17}{27}}.
</span></p>
<ol start="2" type="a">
<li>The probability of no red is</li>
</ol>
<p><span class="math display">
P(\text{no red})=\frac13\frac59+\frac23\frac{\binom52}{\binom92}
=\frac5{27}+\frac5{27}=\frac{10}{27}.
</span></p>
<p>Therefore</p>
<span class="math display">
P(H\mid\text{no red})=\frac{(1/3)(5/9)}{10/27}
=\boxed{\frac12}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2024/2024/qp-202406-mathematics-p52.pdf, Q2(a–b), with the corresponding 9709/52/M/J/24 mark scheme.
</div>
</section>
</div>
<div id="p5-prob-q10" class="question-card">
<section id="question-10-970953mj24-q3ab" class="level3">
<h3 class="anchored" data-anchor-id="question-10-970953mj24-q3ab">Question 10 · 9709/53/M/J/24 Q3(a–b)</h3>
<p>Box A contains 6 green balls and 3 yellow balls.</p>
<p>Box B contains 4 green balls and <span class="math inline">x</span> yellow balls.</p>
<p>A ball is chosen at random from box A and placed in box B. A ball is then chosen at random from box B.</p>
<ol type="a">
<li>Draw a tree diagram to represent this information, showing the probability on each of the branches. <strong>[4]</strong></li>
</ol>
<p>The probability that both the balls chosen are the same colour is <span class="math inline">\frac8{15}</span>.</p>
<ol start="2" type="a">
<li>Find the value of <span class="math inline">x</span>. <strong>[3]</strong></li>
</ol>
<details class="answer-panel">
<summary>
Show detailed mark scheme answer
</summary>
<ol type="a">
<li>The first branches are green <span class="math inline">6/9=2/3</span> and yellow <span class="math inline">3/9=1/3</span>. If green is transferred, box B has 5 green and <span class="math inline">x</span> yellow balls; if yellow is transferred, it has 4 green and <span class="math inline">x+1</span> yellow balls. The second branches are therefore</li>
</ol>
<p><span class="math display">
\begin{array}{c|cc}
&amp;\text{green from B}&amp;\text{yellow from B}\\ \hline
\text{green transferred}&amp;\dfrac5{x+5}&amp;\dfrac{x}{x+5}\\[6pt]
\text{yellow transferred}&amp;\dfrac4{x+5}&amp;\dfrac{x+1}{x+5}
\end{array}
</span></p>
<ol start="2" type="a">
<li>“Same colour” means green-green or yellow-yellow:</li>
</ol>
<p><span class="math display">
\frac23\frac5{x+5}+\frac13\frac{x+1}{x+5}=\frac8{15}.
</span></p>
<p>Thus</p>
<span class="math display">
\frac{x+11}{3(x+5)}=\frac8{15}
\implies 15x+165=24x+120
\implies \boxed{x=5}.
</span>
</details>
<div class="source-line">
<strong>Source:</strong> PastPaper/2024/2024/qp-202406-mathematics-p53.pdf, Q3(a–b), with the corresponding 9709/53/M/J/24 mark scheme.
</div>
</section>
</div>


</section>

</main> <!-- /main -->
<script>
document.querySelectorAll('.done-toggle input').forEach((box) => {
  const key = box.dataset.progress;
  if (key && localStorage.getItem('cie-9709-' + key) === '1') box.checked = true;
  box.addEventListener('change', () => {
    if (key) localStorage.setItem('cie-9709-' + key, box.checked ? '1' : '0');
    box.closest('.question-card, .worked-example')?.classList.toggle('is-complete', box.checked);
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../paper-5/permutations-and-combinations.html" class="pagination-link" aria-label="5.2 Permutations and combinations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">5.2 Permutations and combinations</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../paper-5/discrete-random-variables.html" class="pagination-link" aria-label="5.4 Discrete random variables">
        <span class="nav-page-text">5.4 Discrete random variables</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>